### ISSUE TITLE
Identifiers starting with digits are no longer supported after scanner rewrite

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/hil#40] opened 2016-12-08 16:10 UTC
(As reported in hashicorp/terraform#10597 .)

As of the scanner rewrite, it's now treating the sequence `var.1x1` as (`IDENTIFIER`, `DOT`, `INTEGER`, `IDENTIFIER`), which then causes a parse error. This is a change from the previous scanner, most likely because the old scanner treated this entire sequence (including the intermediate period) as a single token.

I suppose that either the code that deals with integers needs to "scan ahead" to see if any letters follow, falling back on the identifier scanner instead if so, or the parser needs to get a bit smarter and tolerate an integer immediately followed by an identifier as a valid part of a variable name, similarly to how we tolerate integers in `foo.1.baz` sequences. At first glance the first option seems better since the latter would accidentally tolerate weird sequences like `var.1 x1` as a single variable name.

**Comment by mitchellh** [comment] 2016-12-08 16:38
I support the first option. This is how I supported "var.a-b" I think.

**Comment by apparentlymart** [comment] 2016-12-08 17:07
I can have a look at this at the weekend, but I'm not sure how that interacts with 0.8 release plans. :confounded:

**Comment by mitchellh** [comment] 2016-12-08 17:45
See https://github.com/hashicorp/terraform/issues/10597#issuecomment-265805001

I'm going to just make this defined behavior. Identifiers shouldn't begin with numbers, it makes other parsing issues much worse.

**Comment by mitchellh** [comment] 2016-12-08 17:46
Ugh but I guess the issue is that the identifier is NOT starting with a number. The identifier is actually "var.1x1". 😖  Crap. Reopening.

**Comment by apparentlymart** [comment] 2016-12-08 18:31
Well I guess that depends on how you think about it. It's true that in old HIL the whole thing `var.1x1` was an identifier. I changed that so that now the *parser* deals with that, with the scanner producing separate tokens for the periods, with my rationale being that it's more intuitive to think of the period as being an operator and we can generate better error messages in the parser because we have more context to work with.

So I think your philosophical question here is still valid: should it be possible to have a variable whose name starts with a number?

In practice I *think* we can scan this unambigiously, but at the cost of some complexity in the (already rather complex) scanner.

**Comment by apparentlymart** [comment] 2016-12-08 18:56
Once I started thinking about this I couldn't stop thinking about it, so here's some notes, mostly just directed at myself...

Rather than having separate functions for scanning identifiers and numbers, perhaps we can instead just have a single function that scans combinations of letters, digits and periods. Scan forward while keeping track of "have seen digits", "have seen letters", "have seen periods". Then we can use those flags to figure out as we go along what kind of token we're talking about. For example:

* If we see letters after we've seen digits but *before* we see any periods, continue until we reach a non-digit/non-letter character and classify as `IDENTIFIER`.
* If we see one period after seeing at least one digit and no letters, continue until we reach a non-digit character and classify as `FLOAT`.
* If we reach a non-digit/non-letter/non-period character before we've seen any periods or letters, stop immediately and classify as `INTEGER`.

That way we remove the artificial constraint that we need to distinguish between `IDENTIFIER` and `INTEGER`/`FLOAT` with only one token of lookahead.

This has some potentially-surprising results, which I suppose you might consider to be "ambiguous" even though they are entirely-deterministic. For example: `foo.bar.1.2.baz` would scan as (ident, dot, ident, dot, float, dot, ident), which would then be a syntax error. In the longer term perhaps we address this by making the indexing syntax work for that scenario, which would be a more consistent way of writing it anyway though it requires some more serious adjustments to the HIL implementation and to Terraform itself.

Perhaps the root mistake here was splitting the variable tokens up into ident/dot sequences in the first place, and we should just undo that and revert to the previous parsing model...

**Comment by VladRassokhin** [comment] 2016-12-08 20:47
Maybe it would be easier to do some AST transformation after lexing and just before parsing (or right in parser)? E.g. collapse `Integer,Identifier` to `Identifier`?
Anyway I'd vote for simple solution: forbid such identifiers starting with number :)

**Comment by VladRassokhin** [comment] 2016-12-08 21:01
BTW: There more fun:
```tf
variable "1x1" {
}
variable "-x2" {
}
variable "*x3" {
}
output "x1" {
  value = "${var.1x1}"
}
output "x2" {
  value = "${var.-x2}"
}
output "x3" {
  value = "${var.*x3}"
}
```
All three cases are seem to be valid variable names since `terraform validate` says nothing about them.
If you unquote variable identifiers, e.g.
```tf
variable 1x1 {
}
variable -x2 {
}
variable *x3 {
}
```
Terraform cannot parse that: `Error loading files Error parsing a.tf: At 1:10: expected: IDENT | STRING | ASSIGN | LBRACE got: NUMBER`

**Comment by VladRassokhin** [comment] 2016-12-08 21:17
I've another idea how to workaround that: use quotes, e.g.
```tf
variable "1x1" {
}
output "x1" {
  value = "${var."1x1"}"
}
```
Terraform does not support that for now, but that approach looks promising. Simple math `1-1` won't mess up.
// Sorry for disturbing by posting so much comments.

**Comment by apparentlymart** [comment] 2016-12-08 21:48
Ugh. I guess Terraform just doesn't do any validation of variable names at all, and then historically HIL allowed arbitrary combinations of letters, digits, dots, dashes and stars.

@mitchellh it feels to me like we should impose some tighter rules on Terraform variable names for 0.8, to stop some of these silly cases with leading stars and dashes. I'm still less sure about allowing variable names starting with digits since that does seem to be somewhat useful but agreed that it *does* make parsing simpler and is consistent with how things behave in other languages.

**Comment by jbardin** [comment] 2016-12-08 22:18
IMHO, I think quoted identifiers should have the same restrictions as unquoted ones, since they are both often allowed in the same positions in HCL.

**Comment by mitchellh** [comment] 2016-12-08 22:36
@jbardin The quoted ones are actually not identifiers, they're strings and parsed as strings. We allow them interchangeably mostly historically but they could just as easily just be semantic errors in Terraform's config parsing.

**Comment by mitchellh** [comment] 2016-12-09 04:17
https://github.com/hashicorp/terraform/pull/10628

I'm going to close this in favor of that for now. Until a reasonable possibility for this pops up I think we're in an okay place around this behavior.

**Closed by mitchellh** 2016-12-09 04:17 UTC

**Comment by kjmkznr** [comment] 2016-12-09 04:35
Thanks!
